// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rblftmvlnpupfqxdvcec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJibGZ0bXZsbnB1cGZxeGR2Y2VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NTUxNjYsImV4cCI6MjA1ODEzMTE2Nn0.fLSSaLtwXnmICn7hQlpPl-JZxUEpvHhfDBWpHsvsoK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);